# Generated by Django 5.0.6 on 2024-06-07 03:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_advancedformsetting'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailstreamforms', '0004_remove_form_error_message_remove_form_template_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(default='Liste des formulaires', help_text='Descrition de la page des formulaire, visible par le public')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='page_ptr',
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wagtailstreamforms.form')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='AdvancedFormSetting',
        ),
        migrations.DeleteModel(
            name='BasicPage',
        ),
    ]
