# Generated by Django 5.0.6 on 2024-06-07 03:05

import modelcluster.fields
import wagtail.fields
import wagtailstreamforms.models.form
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0003_alter_form_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='form',
            name='process_form_submission_hooks',
        ),
        migrations.RemoveField(
            model_name='form',
            name='template_name',
        ),
        migrations.AddField(
            model_name='form',
            name='email_author_body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='form',
            name='email_author_subject',
            field=models.CharField(blank=True, help_text='Laissez vide pour ne pas envoyer de message.', max_length=255, verbose_name='Sujet'),
        ),
        migrations.AddField(
            model_name='form',
            name='email_orga_body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='form',
            name='email_orga_members',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Destinataires'),
        ),
        migrations.AddField(
            model_name='form',
            name='email_orga_subject',
            field=models.CharField(blank=True, help_text='Laissez vide pour ne pas envoyer de message.', max_length=255, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(default=wagtailstreamforms.models.form.get_default_slug, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='form',
            name='submit_button_text',
            field=models.CharField(default='Envoyer', max_length=100, verbose_name='Submit button text'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formsubmissionfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
