# Generated by Django 5.0.6 on 2024-06-05 13:44

import wagtailstreamforms.models.form
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0003_alter_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='form',
            name='template_name',
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(default=wagtailstreamforms.models.form.get_default_slug, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='form',
            name='submit_button_text',
            field=models.CharField(default='Envoyer', max_length=100, verbose_name='Submit button text'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formsubmissionfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
