# Generated by Django 5.0.6 on 2024-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0003_alter_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(help_text='Used to identify the form in template tags', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='form',
            name='template_name',
            field=models.CharField(choices=[('streamforms/form_block.html', 'Simple')], default='Simple', max_length=255, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formsubmissionfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
